/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/signin": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: {
				content: {
					"application/json": components["schemas"]["SignInSchema"]
				}
			}
			responses: {
				/** @description Login success */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						"application/json": components["schemas"]["StaffInfo"]
					}
				}
				/** @description Login failed */
				401: {
					headers: {
						[name: string]: unknown
					}
					content: {
						"application/json": components["schemas"]["SignInError"]
					}
				}
			}
		}
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	"/register": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: {
				content: {
					"application/json": {
						/** Format: email */
						email: string
						firstName: string
						lastName: string
						password: string
					}
				}
			}
			responses: {
				/** @description Register success */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						"application/json": components["schemas"]["RegisterResult"]
					}
				}
				/** @description Register failed */
				409: {
					headers: {
						[name: string]: unknown
					}
					content: {
						"application/json": components["schemas"]["RegisterResult"]
					}
				}
			}
		}
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	"/account/signout": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post?: never
		delete: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Sign out */
				204: {
					headers: {
						[name: string]: unknown
					}
					content?: never
				}
			}
		}
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	"/verify/list": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description List all unverfied staff */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						"application/json": components["schemas"]["UnverifiedStaffInfo"][]
					}
				}
			}
		}
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	"/tenants/list": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description List all of the Tenants (user table for now) */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						"application/json": components["schemas"]["TenantsInfo"][]
					}
				}
			}
		}
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
}
export type webhooks = Record<string, never>
export interface components {
	schemas: {
		StaffInfo: {
			/** Format: email */
			email: string
			firstName: string
			lastName: string
		}
		SignInError: {
			message: string
		}
		SignInSchema: {
			/** Format: email */
			email: string
			password: string
		}
		RegisterResult: {
			message: string
		}
		UnverifiedStaffInfo: {
			staffID: number
			/** Format: email */
			email: string
			firstName: string
			lastName: string
		}
		TenantsInfo: {
			id: number
			username: string
			firstname: string
			lastname: string
			active: boolean | null
			phone: string | null
			email: string | null
		}
	}
	responses: never
	parameters: never
	requestBodies: never
	headers: never
	pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
